"""create_scans_and_findings_tables

Revision ID: 3f41882961e9
Revises: 78287fac4609
Create Date: 2026-03-16 14:14:04.432731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f41882961e9'
down_revision: Union[str, None] = '78287fac4609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('repo_id', sa.CHAR(length=36), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('files_scanned', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_repo_id'), 'scans', ['repo_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('scan_id', sa.CHAR(length=36), nullable=False),
    sa.Column('identity_hash', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('vulnerability_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('code_snippet', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_identity_hash'), 'findings', ['identity_hash'], unique=False)
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_identity_hash'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_scans_repo_id'), table_name='scans')
    op.drop_table('scans')
    # ### end Alembic commands ###
