"""create_triage_statuses_table

Revision ID: 54fc2f1e5848
Revises: 3f41882961e9
Create Date: 2026-03-16 15:32:32.788922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54fc2f1e5848'
down_revision: Union[str, None] = '3f41882961e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_statuses',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('finding_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'user_id', name='uq_finding_user_triage')
    )
    op.create_index(op.f('ix_triage_statuses_finding_id'), 'triage_statuses', ['finding_id'], unique=False)
    op.create_index(op.f('ix_triage_statuses_user_id'), 'triage_statuses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_statuses_user_id'), table_name='triage_statuses')
    op.drop_index(op.f('ix_triage_statuses_finding_id'), table_name='triage_statuses')
    op.drop_table('triage_statuses')
    # ### end Alembic commands ###
