"""create_remediations_table

Revision ID: 98bf3f065df8
Revises: aa25e4690a33
Create Date: 2026-03-16 16:24:51.717974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98bf3f065df8'
down_revision: Union[str, None] = 'aa25e4690a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remediations',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('finding_id', sa.CHAR(length=36), nullable=False),
    sa.Column('fixed_code', sa.String(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remediations')
    # ### end Alembic commands ###
