"""use_timezone_aware_datetimes

Revision ID: b18d884b20c0
Revises: ff1cef02581b
Create Date: 2026-03-16 18:01:58.899972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18d884b20c0'
down_revision: Union[str, None] = 'ff1cef02581b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
