"""add_github_token_to_repositories

Revision ID: f4bfda0936e6
Revises: 54fc2f1e5848
Create Date: 2026-03-16 16:02:47.258900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4bfda0936e6'
down_revision: Union[str, None] = '54fc2f1e5848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('github_token_encrypted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'github_token_encrypted')
    # ### end Alembic commands ###
