"""add_language_to_findings

Revision ID: ff1cef02581b
Revises: 98bf3f065df8
Create Date: 2026-03-16 16:26:20.047390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1cef02581b'
down_revision: Union[str, None] = '98bf3f065df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('language', sa.String(), nullable=False, server_default='python'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'language')
    # ### end Alembic commands ###
